#!/usr/bin/env python3
"""
Scans the photos/ folder, reads GPS coordinates from each photo's EXIF data,
and writes spots.js automatically. No manual coordinate entry needed.

Usage:
    python3 build_spots.py

Requires photos to have location data embedded (phone GPS must have been
enabled when the photo was taken). Photos without GPS data are skipped
with a warning.
"""

import os
import sys
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS

PHOTOS_DIR = "photos"
OUTPUT_FILE = "spots.js"


def get_exif_gps(image_path):
    try:
        img = Image.open(image_path)
        exif_data = img._getexif()
    except Exception:
        return None

    if not exif_data:
        return None

    gps_info = {}
    for tag_id, value in exif_data.items():
        tag = TAGS.get(tag_id, tag_id)
        if tag == "GPSInfo":
            for gps_tag_id, gps_value in value.items():
                gps_tag = GPSTAGS.get(gps_tag_id, gps_tag_id)
                gps_info[gps_tag] = gps_value

    if not gps_info:
        return None

    def to_degrees(value):
        d, m, s = value
        return float(d) + float(m) / 60.0 + float(s) / 3600.0

    try:
        lat = to_degrees(gps_info["GPSLatitude"])
        if gps_info.get("GPSLatitudeRef") == "S":
            lat = -lat

        lng = to_degrees(gps_info["GPSLongitude"])
        if gps_info.get("GPSLongitudeRef") == "W":
            lng = -lng

        return round(lat, 6), round(lng, 6)
    except (KeyError, ValueError, ZeroDivisionError):
        return None


def main():
    if not os.path.isdir(PHOTOS_DIR):
        print(f"No '{PHOTOS_DIR}' folder found. Create it and add photos first.")
        sys.exit(1)

    valid_extensions = (".jpg", ".jpeg", ".png", ".heic")
    files = sorted(
        f for f in os.listdir(PHOTOS_DIR)
        if f.lower().endswith(valid_extensions)
    )

    if not files:
        print(f"No photos found in '{PHOTOS_DIR}/'.")
        sys.exit(1)

    spots = []
    skipped = []

    for filename in files:
        path = os.path.join(PHOTOS_DIR, filename)
        gps = get_exif_gps(path)
        if gps:
            lat, lng = gps
            spots.append((filename, lat, lng))
        else:
            skipped.append(filename)

    with open(OUTPUT_FILE, "w", encoding="utf-8") as f:
        f.write("// Auto-generated by build_spots.py from photo GPS data.\n")
        f.write("// Re-run build_spots.py after adding new photos.\n")
        f.write("const SPOTS = [\n")
        for filename, lat, lng in spots:
            f.write(f'  {{ photo: "photos/{filename}", lat: {lat}, lng: {lng} }},\n')
        f.write("];\n")

    print(f"Wrote {len(spots)} spots to {OUTPUT_FILE}")
    if skipped:
        print(f"\nSkipped {len(skipped)} photo(s) with no GPS data:")
        for filename in skipped:
            print(f"  - {filename}")
        print("\n(Make sure location services were on when these were taken,")
        print(" or add their coordinates to spots.js manually.)")


if __name__ == "__main__":
    main()
